# Generated by Django 4.2.3 on 2023-11-11 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Company_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("contact", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateField(blank=True, max_length=255, null=True)),
                ("End_date", models.DateField(blank=True, max_length=255, null=True)),
                ("gst_type", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="image/patient"),
                ),
                ("superadmin_approval", models.IntegerField(default=0, null=True)),
                ("Distributor_approval", models.IntegerField(default=0, null=True)),
                (
                    "reg_action",
                    models.CharField(
                        blank=True, default="self", max_length=255, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_hsn", models.PositiveIntegerField(null=True)),
                ("item_unit", models.CharField(max_length=255)),
                ("item_taxable", models.CharField(max_length=255)),
                ("item_gst", models.CharField(max_length=255, null=True)),
                ("item_igst", models.CharField(max_length=255, null=True)),
                ("item_sale_price", models.PositiveIntegerField()),
                ("item_purchase_price", models.PositiveBigIntegerField()),
                ("item_opening_stock", models.PositiveBigIntegerField(default=0)),
                ("item_current_stock", models.PositiveBigIntegerField(default=0)),
                ("item_at_price", models.PositiveBigIntegerField(default=0)),
                ("item_date", models.DateField()),
                ("item_min_stock_maintain", models.PositiveBigIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="payment_terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_terms_number", models.IntegerField(blank=True, null=True)),
                (
                    "payment_terms_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("days", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseBill",
            fields=[
                (
                    "billno",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="BILLID"
                    ),
                ),
                ("partyname", models.CharField(max_length=100)),
                ("email", models.CharField(default="", max_length=100)),
                ("billdate", models.DateField()),
                ("duedate", models.DateField()),
                ("address", models.CharField(default="", max_length=255)),
                ("supplystate", models.CharField(default="", max_length=100)),
                ("pay_method", models.CharField(default="", max_length=255, null=True)),
                ("cheque_no", models.CharField(default="", max_length=255, null=True)),
                ("upi_no", models.CharField(default="", max_length=255, null=True)),
                ("bank_no", models.CharField(default="", max_length=255, null=True)),
                ("subtotal", models.IntegerField(default=0, null=True)),
                ("igst", models.CharField(default=0, max_length=100, null=True)),
                ("cgst", models.CharField(default=0, max_length=100, null=True)),
                ("sgst", models.CharField(default=0, max_length=100, null=True)),
                ("taxamount", models.CharField(default=0, max_length=100, null=True)),
                ("adjust", models.CharField(default=0, max_length=100, null=True)),
                ("grandtotal", models.FloatField(default=0, null=True)),
                ("advance", models.CharField(blank=True, max_length=255, null=True)),
                ("balance", models.CharField(blank=True, max_length=255, null=True)),
                ("tot_inv_no", models.IntegerField(default=0, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trans_type", models.CharField(max_length=255)),
                (
                    "trans_invoice",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("trans_user_name", models.CharField(max_length=255)),
                ("trans_date", models.DateTimeField()),
                ("trans_qty", models.PositiveBigIntegerField(default=0)),
                ("trans_current_qty", models.PositiveBigIntegerField(default=0)),
                ("trans_adjusted_qty", models.PositiveBigIntegerField(default=0)),
                ("trans_price", models.PositiveBigIntegerField(default=0)),
                ("trans_status", models.CharField(max_length=255)),
                (
                    "trans_created_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.itemmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="staff_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=100, null=True)),
                ("user_name", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="image/staff"),
                ),
                ("Action", models.IntegerField(default=0, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseBillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("hsn", models.CharField(max_length=100)),
                ("qty", models.IntegerField(default=0, null=True)),
                ("price", models.CharField(max_length=100)),
                ("total", models.IntegerField(default=0, null=True)),
                ("tax", models.CharField(max_length=100)),
                ("discount", models.CharField(default=0, max_length=100, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
                (
                    "purchasebill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.purchasebill",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=100)),
                ("gst_no", models.CharField(blank=True, max_length=100, null=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_type", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "openingbalance",
                    models.CharField(
                        blank=True, default="0", max_length=100, null=True
                    ),
                ),
                ("payment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "creditlimit",
                    models.CharField(
                        blank=True, default="0", max_length=100, null=True
                    ),
                ),
                (
                    "current_date",
                    models.DateField(blank=True, max_length=255, null=True),
                ),
                ("End_date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "additionalfield1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "additionalfield2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "additionalfield3",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="modules_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sales_invoice",
                    models.CharField(default=0, max_length=100, null=True),
                ),
                ("Estimate", models.IntegerField(default=0, null=True)),
                ("Payment_in", models.IntegerField(default=0, null=True)),
                ("sales_order", models.IntegerField(default=0, null=True)),
                ("Delivery_challan", models.IntegerField(default=0, null=True)),
                ("sales_return", models.IntegerField(default=0, null=True)),
                ("Purchase_bills", models.IntegerField(default=0, null=True)),
                ("Payment_out", models.IntegerField(default=0, null=True)),
                ("Purchase_order", models.IntegerField(default=0, null=True)),
                ("Purchase_return", models.IntegerField(default=0, null=True)),
                ("Bank_account", models.IntegerField(default=0, null=True)),
                ("Cash_in_hand", models.IntegerField(default=0, null=True)),
                ("cheques", models.IntegerField(default=0, null=True)),
                ("Loan_account", models.IntegerField(default=0, null=True)),
                ("update_action", models.IntegerField(default=0, null=True)),
                ("status", models.CharField(default="New", max_length=100, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Distributors_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distributor_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="image/distributor"
                    ),
                ),
                ("start_date", models.DateField(blank=True, max_length=255, null=True)),
                ("End_date", models.DateField(blank=True, max_length=255, null=True)),
                ("Log_Action", models.IntegerField(default=0, null=True)),
                (
                    "payment_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.payment_terms",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="Distributors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vyaparapp.distributors_details",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="dateperiod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vyaparapp.payment_terms",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
