# Generated by Django 4.2.3 on 2023-11-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasebill",
            name="phno",
            field=models.CharField(default="", max_length=255),
        ),
    ]
