# Generated by Django 4.2.3 on 2023-11-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchasebillitem", name="tax",),
        migrations.RemoveField(model_name="purchaseorderitem", name="tax",),
    ]
