# Generated by Django 4.2.4 on 2023-09-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0002_company_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
