# Generated by Django 4.2.3 on 2023-11-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0002_purchasebill_phno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasebill", old_name="tot_inv_no", new_name="tot_bill_no",
        ),
    ]
