# Generated by Django 4.2.3 on 2023-11-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0003_rename_tot_inv_no_purchasebill_tot_bill_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasebill", old_name="partyname", new_name="party",
        ),
    ]
