# Generated by Django 3.2.21 on 2023-10-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0003_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_details',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='business_name',
            new_name='dateperiod',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='company_email',
            new_name='gst_no',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='company_type',
            new_name='gst_type',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='industry_type',
            new_name='pan_number',
        ),
        migrations.AddField(
            model_name='company_details',
            name='Action',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='End_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='start_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/staff')),
                ('Action', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company_details')),
            ],
        ),
    ]
