# Generated by Django 4.2.3 on 2023-11-12 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0004_rename_partyname_purchasebill_party"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchasebill", name="address",),
        migrations.RemoveField(model_name="purchasebill", name="email",),
        migrations.RemoveField(model_name="purchasebill", name="phno",),
        migrations.AlterField(
            model_name="purchasebill",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vyaparapp.party"
            ),
        ),
    ]
