# Generated by Django 4.2.3 on 2023-11-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0005_remove_purchasebill_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchasebill", name="duedate",),
    ]
