# Generated by Django 3.2.21 on 2023-10-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0005_auto_20231017_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_list',
            name='status',
            field=models.CharField(default='New', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='modules_list',
            name='update_action',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='staff_details',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
