# Generated by Django 4.2.3 on 2023-11-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0006_remove_purchasebill_duedate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasebill", old_name="supplystate", new_name="supplypalce",
        ),
    ]
