# Generated by Django 4.2.3 on 2023-11-13 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vyaparapp", "0007_rename_supplystate_purchasebill_supplypalce"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasebill",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="purchasebill",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vyaparapp.company",
            ),
        ),
    ]
