# Generated by Django 4.2.3 on 2023-11-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0008_purchasebill_user_alter_purchasebill_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasebillitem", old_name="item", new_name="product",
        ),
    ]
