# Generated by Django 3.2.21 on 2023-11-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vyaparapp', '0008_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_hsn', models.PositiveIntegerField(null=True)),
                ('item_unit', models.CharField(max_length=255)),
                ('item_taxable', models.CharField(max_length=255)),
                ('item_gst', models.CharField(max_length=255, null=True)),
                ('item_igst', models.CharField(max_length=255, null=True)),
                ('item_sale_price', models.PositiveIntegerField()),
                ('item_purchase_price', models.PositiveBigIntegerField()),
                ('item_opening_stock', models.PositiveBigIntegerField(default=0)),
                ('item_at_price', models.PositiveBigIntegerField(default=0)),
                ('item_date', models.DateField()),
                ('item_min_stock_maintain', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_invoice', models.PositiveBigIntegerField(blank=True, null=True)),
                ('trans_user_name', models.CharField(max_length=255)),
                ('trans_date', models.DateTimeField()),
                ('trans_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_current_qty', models.PositiveBigIntegerField(default=0)),
                ('trans_price', models.PositiveBigIntegerField(default=0)),
                ('trans_status', models.CharField(max_length=255)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.itemmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
