# Generated by Django 3.2.21 on 2023-11-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0009_itemmodel_transactionmodel_unitmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_current_stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='trans_adjusted_qty',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
