# Generated by Django 4.2.3 on 2023-11-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0010_purchasebill_party_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebill",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vyaparapp.staff_details",
            ),
        ),
    ]
