# Generated by Django 4.2.3 on 2023-11-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0011_alter_purchasebill_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchasebill", old_name="user", new_name="staff",
        ),
    ]
