# Generated by Django 4.2.3 on 2023-11-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0012_rename_user_purchasebill_staff"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchasebill", name="party_balance",),
    ]
