# Generated by Django 4.2.3 on 2023-11-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0013_remove_purchasebill_party_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebillitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vyaparapp.itemmodel"
            ),
        ),
    ]
