# Generated by Django 4.2.3 on 2023-11-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0014_alter_purchasebillitem_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchasebillitem", name="hsn",),
        migrations.RemoveField(model_name="purchasebillitem", name="price",),
    ]
