# Generated by Django 4.2.3 on 2023-11-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0017_purchasebilltransactionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasebilltransactionhistory",
            name="action",
            field=models.CharField(
                choices=[("Created", "Created"), ("Updated", "Updated")], max_length=20
            ),
        ),
    ]
