# Generated by Django 4.2.3 on 2023-11-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0019_bankmodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="purchasebill", name="bank_no",),
    ]
