# Generated by Django 4.2.3 on 2023-11-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0021_purchaseorder_purchaseorderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder", old_name="tot_bill_no", new_name="tot_ord_no",
        ),
    ]
