# Generated by Django 4.2.3 on 2023-11-21 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0022_rename_tot_bill_no_purchaseorder_tot_ord_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderTransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("Created", "Created"), ("Updated", "Updated")],
                        max_length=20,
                    ),
                ),
                ("transactiondate", models.DateField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.company",
                    ),
                ),
                (
                    "purchaseorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.purchasebill",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vyaparapp.staff_details",
                    ),
                ),
            ],
        ),
    ]
