# Generated by Django 4.2.3 on 2023-11-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0023_purchaseordertransactionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseordertransactionhistory",
            name="purchaseorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vyaparapp.purchaseorder",
            ),
        ),
    ]
