# Generated by Django 4.2.3 on 2023-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0024_alter_purchaseordertransactionhistory_purchaseorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="convert",
            field=models.IntegerField(default=0),
        ),
    ]
