# Generated by Django 4.2.3 on 2023-11-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0025_purchaseorder_convert"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="convert_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vyaparapp.purchasebill",
            ),
        ),
    ]
