# Generated by Django 4.2.3 on 2023-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vyaparapp", "0026_purchaseorder_convert_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasebill",
            name="duedate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
